name: okteto开发
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
#  watch:
#    types: started
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Set GOPATH
      run: |
        echo "##[set-env name=date;]$(date +%Y%m%d)"
        echo "##[set-env name=NAME;]$(date +%Y%m%d)"
      shell: bash
      
    - uses: actions/checkout@v1
    - name: send-card
      uses: wei/curl@v1
      with:
        args: -X POST http://fk.nbcc.cn/fxsq/mrdk/save.htm
