name: okteto开发
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
#  watch:
#    types: started
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: 'Get Date'
      run: echo "REPORT_DATE=$(date '+%Y-%m-%d %T')" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - name: send-card
      uses: wei/curl@v1
      with:
        args: -X POST http://fk.nbcc.cn/fxsq/mrdk/save.htm
